name: PR

on:
 pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: test
        run: cat $HOME/files.json
      - name: Check file action
        uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}